services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: freight_auction
      POSTGRES_USER: freight_user
      POSTGRES_PASSWORD: example
    volumes:
      - leilao_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis  

    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

volumes:
  leilao_data:



  
